name: Acquire Activation File
on: workflow_dispatch
jobs:
  activation:
    name: Request Manual Activation File
    runs-on: ubuntu-latest
    steps:
      - name: Request Manual Activation File
        id: getActivationFile
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.10f1
          # unityEmail: ${{ secrets.UNITY_EMAIL }}
          # unityPassword: ${{ secrets.UNITY_PASSWORD }}

      - name: Upload Activation File
        uses: actions/upload-artifact@v3
        with:
          name: Unity_v2022.3.10f1.alf
          path: ${{ steps.getActivationFile.outputs.filePath }}
